package com.example.protobuf;

import com.example.protobuf.models.Car;
import com.example.protobuf.models.Person;

public class Sample {

	public static void main(String[] args) {
		Person sam1 = Person.newBuilder()
				.setName("sam")
				.setAge(10)
				.build();

		Person sam2 = Person.newBuilder()
				.setName("sam")
				.setAge(10)
				.build();

		// We cannot override the equals method of autogenerated class.
		// System.out.println(sam1.equals(sam2));

		Car car = Car.newBuilder()
				.setMake("HONDA")
				.setYear(2020)
				.build();

		// System.out.println(car);
		// System.out.println(car.getStyle());

		Person person = Person.newBuilder()
				.build();

		System.out.println(person.getName().equals(""));
		System.out.println(person.getAge());
		System.out.println(person.getFirstCar());
		System.out.println(person.hasFirstCar());
		System.out.println(person.getCarsList());
	}
}
